Repository JeffreyYou/Reddit-Forum, pull requests merged in 2024-02, with the labels that each got.

#6 Update Gateway URI Matching Rule
  .idea/compiler.xml
  .idea/misc.xml
  GatewayService/src/main/resources/application.yml
Labels: bug

#12 BugFix: Backend dev IDEA detect all the modules
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/misc.xml
  .idea/modules.xml
  pom.xml
Labels: bug, enhancement

#19 Frontend dev rebuild
  reddit-frontend/index.html
  reddit-frontend/src/App.tsx
  reddit-frontend/src/components/nav-bar/Navbar.tsx
  reddit-frontend/src/components/nav-bar/style.module.scss
  reddit-frontend/src/components/new-post/NewPost.tsx
  reddit-frontend/src/components/new-post/style.module.scss
  reddit-frontend/src/components/post/Posts.tsx
  reddit-frontend/src/components/post/style.module.scss
  reddit-frontend/src/hooks/index.ts
  reddit-frontend/src/main.tsx
  reddit-frontend/src/pages/home/HomePage.tsx
  reddit-frontend/src/pages/home/style.module.scss
  reddit-frontend/src/pages/login/LoginPage.tsx
  reddit-frontend/src/pages/login/style.module.scss
  reddit-frontend/src/pages/register/RegisterPage.tsx
  reddit-frontend/src/pages/register/style.module.scss
  reddit-frontend/src/router.tsx
  reddit-frontend/src/store/index.ts
  reddit-frontend/src/styles/theme.ts
Labels: enhancement

#25 BugFix: fix cors problems for gateway & user service
  GatewayService/src/main/resources/application.yml
  UserService/src/main/java/com/beaconfire/userservice/config/SecurityConfig.java
  UserService/src/main/java/com/beaconfire/userservice/controller/UserAuthController.java
  UserService/src/main/java/com/beaconfire/userservice/controller/UserMgmtController.java
  UserService/src/main/java/com/beaconfire/userservice/controller/UserProfileController.java
Labels: bug

#33 Feature: User store update
  reddit-frontend/src/pages/user-profile/index.tsx
  reddit-frontend/src/store/interface.ts
  reddit-frontend/src/store/user-store.ts
  reddit-frontend/src/store/util.ts
Labels: enhancement
